import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.job.createMany({
    data: [
      {
        title: 'Senior Developer',
        companyName: 'Tech Corp',
        location: 'Remote',
        jobType: 'FULL_TIME',
        minSalary: 90000,
        maxSalary: 120000,
        description: 'Work on cutting-edge projects',
        requirements: '5+ years of experience',
        responsibilities: 'Lead a team of developers',
        applicationDeadline: new Date('2023-12-31'),
      },
      {
        title: 'Junior Intern',
        companyName: 'Startup Inc',
        location: 'New York',
        jobType: 'INTERNSHIP',
        minSalary: 20000,
        maxSalary: 30000,
        description: 'Learn from the best',
        requirements: 'Basic programming knowledge',
        responsibilities: 'Assist senior developers',
        applicationDeadline: new Date('2023-11-30'),
      },
      {
        title: 'Project Manager',
        companyName: 'Business Solutions',
        location: 'San Francisco',
        jobType: 'CONTRACT',
        minSalary: 70000,
        maxSalary: 90000,
        description: 'Manage client projects',
        requirements: '3+ years of project management experience',
        responsibilities: 'Coordinate with clients and teams',
        applicationDeadline: new Date('2024-01-15'),
      },
      {
        title: 'Data Analyst',
        companyName: 'Data Insights',
        location: 'Chicago',
        jobType: 'PART_TIME',
        minSalary: 40000,
        maxSalary: 60000,
        description: 'Analyze data trends and patterns',
        requirements: 'Experience with SQL and Python',
        responsibilities: 'Create reports and dashboards',
        applicationDeadline: new Date('2024-02-28'),
      },
      {
        title: 'UX Designer',
        companyName: 'Creative Agency',
        location: 'Los Angeles',
        jobType: 'FULL_TIME',
        minSalary: 60000,
        maxSalary: 80000,
        description: 'Design user-friendly interfaces',
        requirements: 'Experience with Figma and Adobe XD',
        responsibilities: 'Collaborate with developers and product managers',
        applicationDeadline: new Date('2024-03-31'),
      },
      {
        title: 'DevOps Engineer',
        companyName: 'Cloud Solutions',
        location: 'Seattle',
        jobType: 'FULL_TIME',
        minSalary: 85000,
        maxSalary: 110000,
        description: 'Maintain and improve CI/CD pipelines',
        requirements: 'Experience with AWS and Docker',
        responsibilities: 'Ensure system reliability and scalability',
        applicationDeadline: new Date('2024-04-15'),
      },
      {
        title: 'Marketing Specialist',
        companyName: 'Brand Builders',
        location: 'Boston',
        jobType: 'PART_TIME',
        minSalary: 30000,
        maxSalary: 50000,
        description: 'Develop marketing strategies',
        requirements: 'Knowledge of SEO and social media marketing',
        responsibilities: 'Create campaigns and analyze performance',
        applicationDeadline: new Date('2024-05-01'),
      },
      {
        title: 'AI Researcher',
        companyName: 'Innovate AI',
        location: 'Remote',
        jobType: 'FULL_TIME',
        minSalary: 100000,
        maxSalary: 150000,
        description: 'Research and develop AI models',
        requirements: 'PhD in Computer Science or related field',
        responsibilities: 'Publish papers and build prototypes',
        applicationDeadline: new Date('2024-06-30'),
      },
      {
        title: 'Customer Support Representative',
        companyName: 'HelpDesk Co',
        location: 'Austin',
        jobType: 'CONTRACT',
        minSalary: 35000,
        maxSalary: 45000,
        description: 'Assist customers with inquiries',
        requirements: 'Strong communication skills',
        responsibilities: 'Resolve customer issues promptly',
        applicationDeadline: new Date('2024-07-15'),
      },
      {
        title: 'Product Manager',
        companyName: 'Tech Innovators',
        location: 'San Diego',
        jobType: 'FULL_TIME',
        minSalary: 95000,
        maxSalary: 130000,
        description: 'Oversee product development lifecycle',
        requirements: 'Experience in product management',
        responsibilities: 'Define product vision and strategy',
        applicationDeadline: new Date('2024-08-31'),
      },
      {
        title: 'Backend Developer',
        companyName: 'IndiaStack',
        location: 'Bangalore',
        jobType: 'FULL_TIME',
        minSalary: 1200000,
        maxSalary: 2000000,
        description:
          'Develop scalable backend solutions for fintech applications',
        requirements: '3+ years of experience with Node.js and MongoDB',
        responsibilities:
          'Design and implement APIs, optimize database performance',
        applicationDeadline: new Date('2024-02-15'),
      },
      {
        title: 'Frontend Engineer',
        companyName: 'DesignHub',
        location: 'Mumbai',
        jobType: 'FULL_TIME',
        minSalary: 1000000,
        maxSalary: 1700000,
        description:
          'Create responsive web applications with modern frameworks',
        requirements: 'Experience with React, Vue.js, or Angular',
        responsibilities:
          'Implement UI designs, ensure cross-browser compatibility',
        applicationDeadline: new Date('2024-03-10'),
      },
      {
        title: 'Data Scientist',
        companyName: 'AnalyticsIndia',
        location: 'Chennai',
        jobType: 'FULL_TIME',
        minSalary: 1500000,
        maxSalary: 2500000,
        description: 'Work on machine learning models for predictive analytics',
        requirements: 'MS/PhD in Computer Science or related field',
        responsibilities: 'Develop algorithms, analyze large datasets',
        applicationDeadline: new Date('2024-01-20'),
      },
      {
        title: 'Mobile App Developer',
        companyName: 'AppWorks',
        location: 'Delhi',
        jobType: 'CONTRACT',
        minSalary: 1100000,
        maxSalary: 1800000,
        description: 'Develop native mobile applications for Android and iOS',
        requirements: 'Experience with Swift, Kotlin, or React Native',
        responsibilities: 'Build features, fix bugs, optimize performance',
        applicationDeadline: new Date('2024-02-28'),
      },
      {
        title: 'Cloud Solutions Architect',
        companyName: 'CloudTech',
        location: 'Hyderabad',
        jobType: 'FULL_TIME',
        minSalary: 2000000,
        maxSalary: 3500000,
        description: 'Design and implement cloud infrastructure solutions',
        requirements: 'AWS/Azure certification and 5+ years experience',
        responsibilities:
          'Architect cloud solutions, ensure security and scalability',
        applicationDeadline: new Date('2024-01-15'),
      },
      {
        title: 'UI/UX Designer',
        companyName: 'DesignCraft',
        location: 'Bangalore',
        jobType: 'PART_TIME',
        minSalary: 800000,
        maxSalary: 1200000,
        description:
          'Create engaging user experiences for web and mobile applications',
        requirements: 'Portfolio showcasing UI/UX projects',
        responsibilities: 'Design interfaces, conduct user research',
        applicationDeadline: new Date('2024-03-20'),
      },
      {
        title: 'DevOps Specialist',
        companyName: 'InfraTech',
        location: 'Chennai',
        jobType: 'FULL_TIME',
        minSalary: 1800000,
        maxSalary: 2800000,
        description: 'Implement and manage CI/CD pipelines',
        requirements: 'Experience with Docker, Kubernetes, and Jenkins',
        responsibilities: 'Automate deployments, monitor system performance',
        applicationDeadline: new Date('2024-02-15'),
      },
      {
        title: 'IT Project Manager',
        companyName: 'SolutionsHub',
        location: 'Mumbai',
        jobType: 'FULL_TIME',
        minSalary: 2200000,
        maxSalary: 3000000,
        description: 'Lead IT projects from inception to completion',
        requirements: 'PMP certification and 7+ years experience',
        responsibilities:
          'Plan projects, manage teams, liaise with stakeholders',
        applicationDeadline: new Date('2024-01-30'),
      },
      {
        title: 'Cybersecurity Analyst',
        companyName: 'SecureNet',
        location: 'Hyderabad',
        jobType: 'FULL_TIME',
        minSalary: 1600000,
        maxSalary: 2400000,
        description:
          'Protect organizational data and systems from cyber threats',
        requirements: 'CISSP certification or equivalent experience',
        responsibilities:
          'Conduct security audits, implement security measures',
        applicationDeadline: new Date('2024-02-10'),
      },
      {
        title: 'Technical Content Writer',
        companyName: 'TechDocs',
        location: 'Delhi',
        jobType: 'PART_TIME',
        minSalary: 600000,
        maxSalary: 900000,
        description: 'Create technical documentation and tutorials',
        requirements: 'Strong writing skills and technical background',
        responsibilities:
          'Write user guides, API documentation, and blog posts',
        applicationDeadline: new Date('2024-03-15'),
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
